
---

#

include:
  - /.gitlab-ci/variables.yml
  - /.gitlab-ci/extends.yml
  #
  # - /.gitlab-ci/stages/prepare.yml
  # - /.gitlab-ci/stages/quality.yml
  # - /.gitlab-ci/stages/register.yml
  # - /.gitlab-ci/stages/notify.yml
  # - /.gitlab-ci/stages/deploy.yml

  - /packages/knex/.gitlab-ci.yml
  - /packages/graphql-server/.gitlab-ci.yml

#

stages:
- "Prepare"
- "Code Quality"
- "Registration"
- "Deploy"
- "Notify Finished Deployment"

#

.prepare_stage: &prepare_stage
  stage: "Prepare"
  dependencies: []

.quality_stage:
  stage: "Code Quality"
  dependencies: []
  except:
    variables:
      - $PRODUCTION
