variables:

  # CI variables
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  GIT_STRATEGY: fetch

  # Infra
  IMAGE_INFRA_BASE_NAME: infra/images-docker

  # Globals
  DOCKER_VERSION: "18"
  PYTHON_VERSION: "3.6-alpine"

  RANCHER_PROJECT_ID: c-gsm8d:p-vdtv7

  KUBERNETES_CPU_REQUEST: 1000m
  KUBERNETES_CPU_LIMIT: 2000m
  KUBERNETES_MEMORY_REQUEST: 1Gi
  KUBERNETES_MEMORY_LIMIT: 2Gi

