#

.prepare_stage: &prepare_stage
  stage: "Prepare"
  dependencies: []

#
#
#
.knex_cache: &knex_cache
  key: "$CI_COMMIT_REF_SLUG-knex-node_modules"
  paths:
    - $CI_PROJECT_DIR/.yarn
    - node_modules
    - packages/knex/node_modules
  policy: pull

Install knex:
  <<: *prepare_stage
  image: node:12-alpine
  cache:
    <<: *knex_cache
    policy: pull-push
  before_script:
    - find packages -maxdepth 1 -type d -not -name knex | tail -n +2 | xargs rm -rf
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile
  artifacts:
    expire_in: 30 mins
    paths:
      - node_modules
      - packages/knex/node_modules


Install graphql-server:
  <<: *prepare_stage
  image: node:12-alpine
  cache:
    key: "$CI_COMMIT_REF_SLUG-graphql-server-node_modules"
    paths:
      - $CI_PROJECT_DIR/.yarn
      - node_modules
      - packages/graphql-server/node_modules
  before_script:
    - find packages -maxdepth 1 -type d -not -name graphql-server | tail -n +2 | xargs rm -rf
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile
  artifacts:
    expire_in: 30 mins
    paths:
      - node_modules
      - packages/graphql-server/node_modules

Lint @emjpm/knex:
  stage: "Code Quality"
  dependencies:
    - Install knex
  image: node:12-alpine
  needs:
    - Install knex
  script:
    - yarn workspace @emjpm/knex lint

Test @emjpm/knex:
  stage: "Code Quality"
  dependencies:
    - Install knex
  image: postgres:10-alpine
  needs:
    - Install knex
  services:
    - name: postgres:10-alpine
  allow_failure: true
  retry: 2
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: test
    DATABASE_URL: psql://localhost:5432/emjpm
  script:
    - sh -x docker/postgres/postgres-init.sh
    - yarn workspace @emjpm/knex test
