#

.prepare_stage: &prepare_stage
  stage: "Prepare"
  dependencies: []
  except:
    variables:
      - $PRODUCTION

#
#
#

install:
  <<: *prepare_stage
  image: node:12-alpine
  cache:
    key: "$CI_COMMIT_REF_SLUG-node_modules"
    paths:
      - $CI_PROJECT_DIR/.yarn
      # - node_modules
      # - packages/*/node_modules
  before_script:
    - rm -rf packages/{api,app,graphql-server,hasura,knex}
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile
