#

.prepare_stage: &prepare_stage
  stage: "Prepare"
  dependencies: []
  except:
    variables:
      - $PRODUCTION

#
#
#

install:
  <<: *prepare_stage
  image: node:12-alpine
  cache:
    key: "$CI_COMMIT_REF_SLUG-node_modules"
    paths:
      - $CI_PROJECT_DIR/.yarn
      # - node_modules
      # - packages/*/node_modules
  before_script:
    - rm -rf packages/{api,app,graphql-server,hasura,knex}
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
    - yarn --frozen-lockfile

.prepare_base_image_scope: &prepare_base_image_scope
  changes:
    - packages/**
    - lerna.json
    - package.json
    - yarn.lock

Register socialgouv/emjpm base image:
  <<: *prepare_stage
  extends: .base_register_stage
  only:
    <<: *prepare_base_image_scope
  variables:
    CONTEXT: .
    DOCKER_BUILD_ARGS: >-
      --shm-size 666M
    IMAGE_NAME: $CI_REGISTRY_IMAGE

Use previous socialgouv/emjpm base image:
  <<: *prepare_stage
  extends: .base_use_previous_image_stage
  except:
    <<: *prepare_base_image_scope
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE

#
#
#

.prepare_postgres_scope: &prepare_postgres_scope
  changes:
    - docker/postgres/**

Register postgres image:
  <<: *prepare_stage
  extends: .base_register_stage
  only:
    <<: *prepare_postgres_scope
  variables:
    CONTEXT: ./docker/postgres
    DOCKER_BUILD_ARGS: ""
    IMAGE_NAME: $CI_REGISTRY_IMAGE/postgres

Use previous postgres image:
  <<: *prepare_stage
  extends: .base_use_previous_image_stage
  except:
    <<: *prepare_postgres_scope
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/postgres
