#

.register_stage: &register_stage
  stage: "Registration"
  dependencies: []
  except: &register_stage_except
    variables:
      - $PRODUCTION

#
#
#

.register_api_scope: &register_api_scope
  changes:
    - packages/api/**

Register api image:
  <<: *register_stage
  extends: .base_register_stage
  only:
    <<: *register_api_scope
  variables:
    CONTEXT: packages/api
    DOCKER_BUILD_ARGS: >-
      --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/api

Use previous api image:
  <<: *register_stage
  extends: .base_use_previous_image_stage
  except:
    <<: *register_stage_except
    <<: *register_api_scope
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/api

#
#
#

.register_app_scope: &register_app_scope
  changes:
    - packages/app/**

Register app image:
  <<: *register_stage
  extends: .base_register_stage
  only:
    <<: *register_app_scope
  variables:
    CONTEXT: packages/app
    DOCKER_BUILD_ARGS: >-
      --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/app

Use previous app image:
  <<: *register_stage
  extends: .base_use_previous_image_stage
  except:
    <<: *register_stage_except
    <<: *register_app_scope
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/app

#
#
#
